CREATE TABLE IF NOT EXISTS `smartfund_user`(
`id` INT UNSIGNED AUTO_INCREMENT KEY COMMENT '用户编号',
`username` VARCHAR(20) NOT NULL UNIQUE COMMENT '用户名',
`password` CHAR(32) NOT NULL COMMENT '密码',
`tel` CHAR(11) NOT NULL UNIQUE COMMENT '电话',
`email` VARCHAR(50) NOT NULL UNIQUE COMMENT '邮箱',
`tt_password` CHAR(32) NOT NULL COMMENT '天天基金密码',
`tt_pay_password` CHAR(32) NOT NULL COMMENT '天天基金支付密码',
`group_name` CHAR(32) NOT NULL DEFAULT  '基础账户资产' COMMENT '基金组合',
`user_grade` VARCHAR(50) NOT NULL DEFAULT 'S1' COMMENT '用户等级',
`device` VARCHAR(20) NOT NULL DEFAULT  'SJE0217722000066'  COMMENT '绑定设备号',
`status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0代表冻结，1代表有效',
`effective_date` DATE NOT NULL DEFAULT '2022-12-30' COMMENT '有效日期'
)ENGINE=INNODB DEFAULT CHARSET=UTF8



CREATE TABLE IF NOT EXISTS `fund_asset`(
 `id` INT UNSIGNED AUTO_INCREMENT KEY COMMENT '唯一id',
 `fund_code` VARCHAR(20) NOT NULL   COMMENT '基金代码',
 `date` DATE NOT NULL  COMMENT '日期',
 `tel` CHAR(32) NOT NULL COMMENT '持有人电话',
 `fund_unit` INT   NOT NULL DEFAULT  0  COMMENT  '全部份额',
 `fund_valid_unit` INT   NOT NULL DEFAULT 0  COMMENT  '可用份额',
 `income` INT   NOT NULL DEFAULT 0 COMMENT '持有收益',
 `income_rate` INT  NOT NULL DEFAULT 0 COMMENT '持有收益率'
)ENGINE=INNODB DEFAULT CHARSET=UTF8
